#! /bin/bash
# HOW TO automate co-author attribution
# 1) At beginning of session, 'enable' a co-author by removing leading '#'
#
# 2.1) Using from command line
#    commit -m "A real commit message$(bash ./Co-Authored-By.sh)"
#
# 2.2) Using in an IDE
#    Use command line to copy co-authors into copy/paste buffer...
#      `./Co-Authored-By.sh)" | pbcopy`
#    ... then use `paste` inside the IDE commit message dialog
#
# 3) Subsequent commits can bring back this command line for simple modification

function cat_co_authored_by {
cat <<CO-AUTHORED-BY
#Co-Authored-By: Gregor Riegler <rieglerg85@gmail.com>
Co-Authored-By: Nitsan Avni <nitsanav@gmail.com>
#Co-Authored-By: Joel Silberman <42779942+jcs-instructor@users.noreply.github.com>
#Co-Authored-By: 4dsherwood <4dsherwood@users.noreply.github.com>
#Co-Authored-By: Blaise Pabon <blaise@gmail.com>
#Co-Authored-By: Michael R. Wolf <MichaelRWolf@att.net>

#Co-Authored-By: Idan Melamed <idanmel@gmail.com>
#Co-Authored-By: Tsvetan Tsvetanov <cpi.cecko@gmail.com>

#Co-Authored-By: Austin Chadwick <austin.chadwick11@gmail.com>
#Co-Authored-By: Rea <reasu@protonmail.com>
#Co-Authored-By: David Campey <campey@gmail.com>
#Co-Authored-by: Zac Ball <zac156@gmail.com>
#Co-Authored-By: Kitastro <admin@metafor.co.za>

# Leave the following line alone!!!
CO-AUTHORED-BY
}


function main {
echo				# Terminate (likely) incomplete line
echo				# Inject blank line
cat_co_authored_by |
    grep -v '#' |
    grep -v '^[[:space:]]*$'
}


main
